[2025-09-04T19:47:47.250-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_sentiment_retrain.check_drift manual__2025-09-05T00:47:39.112652+00:00 [queued]>
[2025-09-04T19:47:47.252-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_sentiment_retrain.check_drift manual__2025-09-05T00:47:39.112652+00:00 [queued]>
[2025-09-04T19:47:47.252-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-04T19:47:47.257-0500] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): check_drift> on 2025-09-05 00:47:39.112652+00:00
[2025-09-04T19:47:47.261-0500] {standard_task_runner.py:57} INFO - Started process 25459 to run task
[2025-09-04T19:47:47.264-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'movie_sentiment_retrain', 'check_drift', 'manual__2025-09-05T00:47:39.112652+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/retrain_pipeline.py', '--cfg-path', '/var/folders/q5/0d_dg10s4m55__wc3fybh0280000gr/T/tmpgbjznqhu']
[2025-09-04T19:47:47.265-0500] {standard_task_runner.py:85} INFO - Job 69: Subtask check_drift
[2025-09-04T19:47:47.282-0500] {task_command.py:416} INFO - Running <TaskInstance: movie_sentiment_retrain.check_drift manual__2025-09-05T00:47:39.112652+00:00 [running]> on host SebastianSamay.local
[2025-09-04T19:47:47.302-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops-team' AIRFLOW_CTX_DAG_ID='movie_sentiment_retrain' AIRFLOW_CTX_TASK_ID='check_drift' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T00:47:39.112652+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-05T00:47:39.112652+00:00'
[2025-09-04T19:47:58.497-0500] {logging_mixin.py:154} INFO - Salida del monitor: ⚠️  No se encontraron datos de referencia. Ejecuta create_reference_data() primero.
[2025-09-04T19:47:58.499-0500] {logging_mixin.py:154} INFO - Errores: /Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
[2025-09-04T19:47:58.500-0500] {logging_mixin.py:154} INFO - Error verificando drift: [Errno 2] No such file or directory: 'monitoring_data/airflow/last_drift_check.json'
[2025-09-04T19:47:58.500-0500] {python.py:194} INFO - Done. Returned value was: skip_retrain
[2025-09-04T19:47:58.500-0500] {python.py:227} INFO - Branch callable return skip_retrain
[2025-09-04T19:47:58.500-0500] {skipmixin.py:173} INFO - Following branch skip_retrain
[2025-09-04T19:47:58.505-0500] {skipmixin.py:239} INFO - Skipping tasks [('retrain_model', -1)]
[2025-09-04T19:47:58.515-0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=movie_sentiment_retrain, task_id=check_drift, execution_date=20250905T004739, start_date=20250905T004747, end_date=20250905T004758
[2025-09-04T19:47:58.545-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-04T19:47:58.555-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
