[2025-09-04T22:37:32.482-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_sentiment_retrain.retrain_model manual__2025-09-05T03:26:37.270000+00:00 [queued]>
[2025-09-04T22:37:32.485-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_sentiment_retrain.retrain_model manual__2025-09-05T03:26:37.270000+00:00 [queued]>
[2025-09-04T22:37:32.485-0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-09-04T22:37:32.490-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrain_model> on 2025-09-05 03:26:37.270000+00:00
[2025-09-04T22:37:32.494-0500] {standard_task_runner.py:57} INFO - Started process 43826 to run task
[2025-09-04T22:37:32.497-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'movie_sentiment_retrain', 'retrain_model', 'manual__2025-09-05T03:26:37.270000+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/retrain_pipeline.py', '--cfg-path', '/var/folders/q5/0d_dg10s4m55__wc3fybh0280000gr/T/tmpygntm__z']
[2025-09-04T22:37:32.499-0500] {standard_task_runner.py:85} INFO - Job 165: Subtask retrain_model
[2025-09-04T22:37:32.514-0500] {task_command.py:416} INFO - Running <TaskInstance: movie_sentiment_retrain.retrain_model manual__2025-09-05T03:26:37.270000+00:00 [running]> on host SebastianSamay.local
[2025-09-04T22:37:32.534-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops-team' AIRFLOW_CTX_DAG_ID='movie_sentiment_retrain' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T03:26:37.270000+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-05T03:26:37.270000+00:00'
[2025-09-04T22:37:32.535-0500] {logging_mixin.py:154} INFO - Proyecto en: /Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3
[2025-09-04T22:37:32.535-0500] {logging_mixin.py:154} INFO - Directorio de trabajo actual: /Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3
[2025-09-04T22:37:32.535-0500] {logging_mixin.py:154} INFO - Iniciando reentrenamiento: logistic_regression_bayesian.pkl
[2025-09-04T22:39:55.125-0500] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-04T22:39:55.186-0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/airflow/dags/retrain_pipeline.py", line 142, in retrain_model
    result = subprocess.run(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1979, in _communicate
    ready = selector.select(timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-09-04T22:39:55.203-0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=movie_sentiment_retrain, task_id=retrain_model, execution_date=20250905T032637, start_date=20250905T033732, end_date=20250905T033955
[2025-09-04T22:39:55.213-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 165 for task retrain_model ((sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('retrain_model', 'movie_sentiment_retrain', 'manual__2025-09-05T03:26:37.270000+00:00', -1, '2025-09-05 03:37:32.482375', '2025-09-05 03:39:55.203127', 142)]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 43826)
