[2025-09-03T20:34:22.060-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_sentiment_retrain.check_drift scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-09-03T20:34:22.063-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_sentiment_retrain.check_drift scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-09-03T20:34:22.063-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-03T20:34:22.068-0500] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): check_drift> on 2025-09-03 00:00:00+00:00
[2025-09-03T20:34:22.072-0500] {standard_task_runner.py:57} INFO - Started process 98499 to run task
[2025-09-03T20:34:22.075-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'movie_sentiment_retrain', 'check_drift', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/retrain_pipeline.py', '--cfg-path', '/var/folders/q5/0d_dg10s4m55__wc3fybh0280000gr/T/tmpewhh1sf4']
[2025-09-03T20:34:22.076-0500] {standard_task_runner.py:85} INFO - Job 3: Subtask check_drift
[2025-09-03T20:34:22.096-0500] {task_command.py:416} INFO - Running <TaskInstance: movie_sentiment_retrain.check_drift scheduled__2025-09-03T00:00:00+00:00 [running]> on host SebastianSamay.local
[2025-09-03T20:34:22.114-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops-team' AIRFLOW_CTX_DAG_ID='movie_sentiment_retrain' AIRFLOW_CTX_TASK_ID='check_drift' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-09-03T20:34:25.830-0500] {logging_mixin.py:154} INFO - Salida del monitor: 
[2025-09-03T20:34:25.831-0500] {logging_mixin.py:154} INFO - Errores: Traceback (most recent call last):
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/monitoring/drift_monitor.py", line 21, in <module>
    import mlflow
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/mlflow/__init__.py", line 44, in <module>
    from mlflow import (
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/mlflow/artifacts/__init__.py", line 11, in <module>
    from mlflow.tracking import _get_store
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/mlflow/tracking/__init__.py", line 8, in <module>
    from mlflow.tracking._model_registry.utils import (
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/mlflow/tracking/_model_registry/utils.py", line 14, in <module>
    from mlflow.store._unity_catalog.registry.rest_store import UcModelRegistryStore
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/mlflow/store/__init__.py", line 1, in <module>
    from mlflow.store.artifact import artifact_repo
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/mlflow/store/artifact/artifact_repo.py", line 8, in <module>
    from mlflow.entities.file_info import FileInfo
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/mlflow/entities/__init__.py", line 6, in <module>
    from mlflow.entities.dataset import Dataset
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/mlflow/entities/dataset.py", line 4, in <module>
    from mlflow.protos.service_pb2 import Dataset as ProtoDataset
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/mlflow/protos/service_pb2.py", line 11, in <module>
    from google.protobuf import service as _service
ImportError: cannot import name 'service' from 'google.protobuf' (/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/google/protobuf/__init__.py)
[2025-09-03T20:34:25.831-0500] {logging_mixin.py:154} INFO - Error verificando drift: [Errno 2] No such file or directory: 'monitoring_data/airflow/last_drift_check.json'
[2025-09-03T20:34:25.831-0500] {python.py:194} INFO - Done. Returned value was: skip_retrain
[2025-09-03T20:34:25.831-0500] {python.py:227} INFO - Branch callable return skip_retrain
[2025-09-03T20:34:25.832-0500] {skipmixin.py:173} INFO - Following branch skip_retrain
[2025-09-03T20:34:25.837-0500] {skipmixin.py:239} INFO - Skipping tasks [('retrain_model', -1)]
[2025-09-03T20:34:25.848-0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=movie_sentiment_retrain, task_id=check_drift, execution_date=20250903T000000, start_date=20250904T013422, end_date=20250904T013425
[2025-09-03T20:34:25.856-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-03T20:34:25.869-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
